### ISSUE TITLE
Suggestion for new python linter / formatting tool: Ruff

### ISSUE THREAD

**Issue by lucasfijen** [lyz-code/blue-book#38]
Hey! Just came across your repo, have had a nice readup, thanks for your work!

You could probably make an endless list of, also nice to mention tools, but here is my take on one:

Small pitch:
I think it would be nice to also mention [ruff](https://docs.astral.sh/ruff/). It's a newly written formatter/linter for python that is written in Rust. It's currently pretty much taking over where black/flake8 used to be, and incorporated a lot of extra add-ons of black/flake8 within its own repository, making it a really clean solution. Also the linter has nice and really fast extensions for vs code, so anyone who now newly starts with setting up a python deck I recommend to have a look at ruff.

Anyways, thanks for your work!

**Comment by lyz-code** [comment]
Hi @lucasfijen, sorry for taking so much time to answer, I was on some sweet holidays ❤ . 

Thanks for your suggestion, ruff has been in my wishlist for a while, and I think my editor (neovim with lazyvim) is using it behind the scenes without my knowledge. 

If you were kind enough to make a pull request to add the information that would be awesome! I know not that many people have contributed to the blue book but it has always been open to contributions, so feel free to suggest all the tools that you want or amend anything that feels wrong.

I'm closing the issue because I'm currently kind of busy and I feel I won't have time to add this information myself.

Thank you for taking the time to open the issue and the energy to improve the blue-book (✿◠‿◠)
